data:
  # Where to save the demos
  save_path: /home/jiafeid/rlbench-failgen/failgen/data
  # The size of the images to save
  image_size: [256, 256]
  # The renderer to use. Either opengl or opengl3. The first has no shadows
  renderer: opengl3
  # The number of episodes to collect per task
  episodes_per_task: 5
  # The image types that will be recorded
  images:
    rgb: True
    depth: True
    mask: True
    point_cloud: True
  # The cameras that we will be enabled
  cameras:
    left_shoulder: True
    right_shoulder: True
    overhead: True
    wrist: True
    front: True
  # Store depth as 0 - 1
  depth_in_meters: False
  # We want to save the masks as rgb encodings.
  masks_as_one_channel: True
  # The set of waypoints for this task
  waypoints: [0,1,2,3,4,5]
failures:
  - type: grasp
    name: fail_grasp
    enabled: False
    waypoints: [1]

  - type: translation_x
    name: trans_x
    enabled: False
    waypoints: [0, 1, 4, 5]
    range: [-0.5, 0.5]

  - type: translation_y
    name: trans_y
    enabled: False
    waypoints: [1, 4, 5]
    range: [-0.5, 0.5]

  - type: translation_z
    name: trans_z
    enabled: False
    waypoints: [0, 1, 5]
    range: [-0.5, 0.5]

  - type: rotation_x
    name: rot_x
    enabled: False
    waypoints: [0, 1, 5]
    range: [-1.57, 1.57]

  - type: rotation_y
    name: rot_y
    enabled: False
    waypoints: [1, 3, 4, 5]
    range: [-1.57, 1.57]

  - type: no_rotation
    name: fail_no_rot
    enabled: False
    waypoints: [2]

  - type: slip
    name: fail_slip
    enabled: False
    waypoints: [2, 3, 4]
    fail_after: 5

  - type: wrong_object
    name: grasp_wrong_object
    enabled: False
    waypoints: [3]
    key_waypoint: waypoint3
    original_name: jar0
    alternatives_names: [jar1]

  - type: wrong_sequence
    name: bad_seq
    enabled: False
    waypoints: [0, 5]

sub-tasks:
  - task_no: 0
    enabled: False
    type: dummy
    targets: [spawn_boundary]
    processes: [waypoint0, waypoint1]
    task_description: [
      'prepare the pre-grasp pose',
    ]
  - task_no: 1
    enabled: False
    type: dummy
    targets: [spawn_boundary]
    processes: [waypoint1, waypoint2]
    task_description: [
      'pick the lid',
      'grasp the lid',
      'use the gripper to pick the lid',
    ]
  - task_no: 2
    enabled: False
    type: dummy
    targets: [close_jar]
    processes: [waypoint2, waypoint3]
    task_description: [
      'transport the lid',
      'transport the lid over the jar',
      'put the lid over the jar',
      'lift the lid from the table over the jar',
      ]
  - task_no: 3
    enabled: False
    type: dummy
    targets: [close_jar]
    processes: [waypoint3, waypoint4]
    task_description: [
      'lift down the lid',
      'put the lid down',
      'lift down the lid of the jar',
      'put the lid down to cover the jar',
      ]
  - task_no: 4
    enabled: False
    type: dummy
    targets: [close_jar]
    processes: [waypoint4, waypoint5]
    task_description: [
      'rotate the lid of the jar to close it',
      'rotate the lid',
      'close the jar',
    ]