data:
  # Where to save the demos
  save_path: /home/jiafeid/rlbench-failgen/failgen/data
  # The size of the images to save
  image_size: [256, 256]
  # The renderer to use. Either opengl or opengl3. The first has no shadows
  renderer: opengl3
  # The number of episodes to collect per task
  episodes_per_task: 5
  # The image types that will be recorded
  images:
    rgb: True
    depth: True
    mask: True
    point_cloud: True
  # The cameras that we will be enabled
  cameras:
    left_shoulder: True
    right_shoulder: True
    overhead: True
    wrist: True
    front: True
  # Store depth as 0 - 1
  depth_in_meters: False
  # We want to save the masks as rgb encodings.
  masks_as_one_channel: True
  # The set of waypoints for this task
  waypoints: [0,1,2,3,4]
failures:
  - type: grasp
    name: fail_grasp
    enabled: False
    waypoints: [2]

  - type: translation_x
    name: trans_x
    enabled: False
    waypoints: [0, 1, 2, 3, 4]
    range: [-0.5, 0.5]

  - type: translation_y
    name: trans_y
    enabled: False
    waypoints: [0, 1, 2, 4]
    range: [-0.5, 0.5]

  - type: translation_z
    name: trans_z
    enabled: False
    waypoints: [0, 1, 2, 3, 4]
    range: [-0.5, 0.5]

  - type: rotation_x
    name: rot_x
    enabled: False
    waypoints: [0, 2, 3]
    range: [-1.57, 1.57]

  - type: rotation_y
    name: rot_y
    enabled: False
    waypoints: [0, 1, 2, 4]
    range: [-1.57, 1.57]

  - type: rotation_z
    name: rot_z
    enabled: False
    waypoints: [0, 2, 3]
    range: [-1.57, 1.57]

  - type: no_rotation
    name: fail_no_rot
    enabled: False
    waypoints: [2]

  - type: slip
    name: fail_slip
    enabled: False
    waypoints: [1]
    fail_after: 5

  - type: wrong_sequence
    name: bad_seq
    enabled: False
    waypoints: [0, 3]

sub-tasks:
  - task_no: 0
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint0, waypoint1]
    task_description: [
      "grasp onto the money",
      "pick the money",
      "grab onto the money"
    ]
  - task_no: 1
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint1, waypoint2]
    task_description: [
      "move the money to a pre insertion pose",
      "get ready to put the money into the safe"
    ]
  - task_no: 2
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint2, waypoint3]
    task_description: [
      "move the money to the right slot"
    ]
  - task_no: 3
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint3, waypoint4]
    task_description: [
      "put the money into the slot within the safe",
      "insert the money into the right slot within the safe"
    ]