data:
  # Where to save the demos
  save_path: /home/jiafeid/rlbench-failgen/failgen/data
  # The size of the images to save
  image_size: [256, 256]
  # The renderer to use. Either opengl or opengl3. The first has no shadows
  renderer: opengl3
  # The number of episodes to collect per task
  episodes_per_task: 5
  # The image types that will be recorded
  images:
    rgb: True
    depth: True
    mask: True
    point_cloud: True
  # The cameras that we will be enabled
  cameras:
    left_shoulder: True
    right_shoulder: True
    overhead: True
    wrist: True
    front: True
  # Store depth as 0 - 1
  depth_in_meters: False
  # We want to save the masks as rgb encodings.
  masks_as_one_channel: True
  # The set of waypoints for this task
  waypoints: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
failures:
  - type: grasp
    name: failure_grasp_pose
    enabled: False
    waypoints: [1]

  - type: translation_x
    name: trans_x
    enabled: False
    waypoints: [0, 1, 2]
    range: [-0.5, 0.5]

  - type: translation_y
    name: trans_y
    enabled: False
    waypoints: [0, 1]
    range: [-0.5, 0.5]

  - type: translation_z
    name: trans_z
    enabled: False
    waypoints: [1]
    range: [-0.5, 0.5]

  - type: rotation_x
    name: rot_x
    enabled: False
    waypoints: [1]
    range: [-1.57, 1.57]

  - type: rotation_y
    name: rot_y
    enabled: False
    waypoints: [1]
    range: [-1.57, 1.57]

  - type: rotation_z
    name: rot_z
    enabled: False
    waypoints: [0, 2]
    range: [-1.57, 1.57]

  - type: no_rotation
    name: no_rot
    enabled: False
    waypoints: [2]

  - type: slip
    name: slippery
    enabled: False
    waypoints: [2]
    fail_after: 4


  - task_no: 6
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint6, waypoint7]
    task_description: [
      "move to the right shoes to target pose",
      "move to the first shoes above the location to place"
    ]
  - task_no: 7
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint7, waypoint8]
    task_description: [
      "place down the right shoes",
      "drop the first shoe"
    ]
  - task_no: 8
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint8, waypoint9]
    task_description: [
      "go to pick the second shoes"
    ]
  - task_no: 9
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint9, waypoint10]
    task_description: [
      "grasp onto the left shoes",
      "pick the left shoes",
      "grab onto second shoes"
    ]
  - task_no: 10
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint10, waypoint11]
    task_description: [
      "lift up the shoes out of the box",
      "pick up the left shoes"
    ]
  - task_no: 11
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint11, waypoint12]
    task_description: [
      "move to the left shoes to target pose",
      "move to the second shoes above the location to place"
    ]
  - task_no: 12
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint12, waypoint13]
    task_description: [
      "place down the left shoes",
      "drop the second shoe"
    ]

