data:
  # Where to save the demos
  save_path: /home/jiafeid/rlbench-failgen/failgen/data
  # The size of the images to save
  image_size: [256, 256]
  # The renderer to use. Either opengl or opengl3. The first has no shadows
  renderer: opengl3
  # The number of episodes to collect per task
  episodes_per_task: 5
  # The image types that will be recorded
  images:
    rgb: True
    depth: True
    mask: True
    point_cloud: True
  # The cameras that we will be enabled
  cameras:
    left_shoulder: True
    right_shoulder: True
    overhead: True
    wrist: True
    front: True
  # Store depth as 0 - 1
  depth_in_meters: False
  # We want to save the masks as rgb encodings.
  masks_as_one_channel: True
  # The set of waypoints for this task
  waypoints: [0, 1, 2, 3, 4, 5, 6, 7]
failures:
  - type: grasp
    name: failure_grasp_pose
    enabled: False
    waypoints: [1]

  - type: translation_x
    name: trans_x
    enabled: False
    waypoints: [0, 1, 2]
    range: [-0.5, 0.5]

  - type: translation_y
    name: trans_y
    enabled: False
    waypoints: [0, 1]
    range: [-0.5, 0.5]

  - type: translation_z
    name: trans_z
    enabled: False
    waypoints: [1]
    range: [-0.5, 0.5]

  - type: rotation_x
    name: rot_x
    enabled: False
    waypoints: [1]
    range: [-1.57, 1.57]

  - type: rotation_y
    name: rot_y
    enabled: False
    waypoints: [1]
    range: [-1.57, 1.57]

  - type: rotation_z
    name: rot_z
    enabled: False
    waypoints: [0, 2]
    range: [-1.57, 1.57]

  - type: no_rotation
    name: no_rot
    enabled: False
    waypoints: [2]

  - type: slip
    name: slippery
    enabled: False
    waypoints: [2]
    fail_after: 4

sub-tasks:
  - task_no: 0
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint0, waypoint1]
    task_description: [
      "grasp onto the remote controller",
      "grab onto the remote controller"
    ]
  - task_no: 1
    enabled: False
    type: dummy
    targets: [ball]
    processes: [waypoint1, waypoint2]
    task_description: [
      "lift up the remote controller",
      "pick up the remote controller"
    ]
  - task_no: 2
    enabled: False
    type: dummy
    targets: [basket_ball_hoop_visual]
    processes: [waypoint2, waypoint3]
    task_description: [
      "orientate the remote controller to face the tv",
      "adjust the the orientation of the remote controller to face the tv"
    ]
  - task_no: 3
    enabled: False
    type: dummy
    targets: [basket_ball_hoop_visual]
    processes: [waypoint3, waypoint4]
    task_description: [
      "put down the remote controller"
    ]
  - task_no: 4
    enabled: False
    type: dummy
    targets: [basket_ball_hoop_visual]
    processes: [waypoint4, waypoint5]
    task_description: [
      "let give of the remote controller"
    ]
  - task_no: 5
    enabled: False
    type: dummy
    targets: [basket_ball_hoop_visual]
    processes: [waypoint5, waypoint6]
    task_description: [
      "move to above the remote controller button"
    ]
  - task_no: 6
    enabled: False
    type: dummy
    targets: [basket_ball_hoop_visual]
    processes: [waypoint6, waypoint7]
    task_description: [
      "press down onto the button on the remote controller",
      "turn on the tv by pressing the remote controller"
    ]